// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RGMS.Lib.Data;

#nullable disable

namespace RGMS.Lib.Data.Migrations
{
    [DbContext(typeof(RgmsDbContext))]
    [Migration("20260512120125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("RGMS.Lib.Data.Entities.DaqChannelSettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxVolts")
                        .HasColumnType("REAL");

                    b.Property<double>("MinVolts")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalChannel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Terminal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneralSettingsId", "ChannelIndex")
                        .IsUnique();

                    b.ToTable("DaqChannelSettings", (string)null);
                });

            modelBuilder.Entity("RGMS.Lib.Data.Entities.GeneralSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("GateOffPhaseDeg")
                        .HasColumnType("REAL");

                    b.Property<double>("GateOnPhaseDeg")
                        .HasColumnType("REAL");

                    b.Property<double>("SampleRateHz")
                        .HasColumnType("REAL");

                    b.Property<int>("SamplesPerChannelPerCallback")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettings", (string)null);
                });

            modelBuilder.Entity("RGMS.Lib.Data.Entities.DaqChannelSettingEntity", b =>
                {
                    b.HasOne("RGMS.Lib.Data.Entities.GeneralSettingsEntity", "GeneralSettings")
                        .WithMany("Channels")
                        .HasForeignKey("GeneralSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralSettings");
                });

            modelBuilder.Entity("RGMS.Lib.Data.Entities.GeneralSettingsEntity", b =>
                {
                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
